version: '3.8'

services:
  server:
    build: 
      context: .

    environment:
      MODE: server

    volumes:
      - ./data/server:/data

  client:
    build: 
      context: .

    environment:
      INTERVAL: 15
      REMOTE: server
      MODE: client

    volumes:
      - ./data/client:/data
